# Generated by Django 5.0.3 on 2024-03-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Tache',
        ),
        migrations.RenameField(
            model_name='tache',
            old_name='title',
            new_name='titre',
        ),
    ]
